```{r}
library(ggplot2)
```

```{r}
data <- read.csv('heart.csv')
data
```

```{r}
max(data$oldpeak)
min(data$oldpeak)
```

```{r}
ggplot(data=data,aes(x=age)) + 
  geom_bar(alpha=0.75,fill="tomato",color="black") +
  ggtitle("Age Distribution")
```

```{r}
ggplot(data=data,aes(x=sex)) + 
  geom_bar(alpha=0.75,fill="orangered",color="black") +
  ggtitle("Counts of Female and Male")
```

```{r}
ggplot(data=data,aes(x=cp)) + geom_bar(alpha=0.75,fill="tan1",color="black") + 
  ggtitle("Chest pain type")
```

```{r}
ggplot(data=data,aes(x=fbs)) + geom_bar(alpha=0.75,fill="cornflowerblue",color="black") +
  ggtitle("fasting blood sugar > 120 mg/dl")
ggplot(data=data,aes(x=restecg)) + geom_bar(alpha=0.75,fill="cornflowerblue",color="black") +
  ggtitle("resting electrocardiographic results")
ggplot(data=data,aes(x=exang)) + geom_bar(alpha=0.75,fill="cornflowerblue",color="black") +
  ggtitle("exercise induced angina")
ggplot(data=data,aes(x=oldpeak)) + geom_bar(alpha=0.75,fill="cornflowerblue",color="black") +
  ggtitle("ST depression induced by exercise relative to rest")
ggplot(data=data,aes(x=slope)) + geom_bar(alpha=0.75,fill="cornflowerblue",color="black") + 
  ggtitle("the slope of the peak exercise ST segment")
ggplot(data=data,aes(x=ca)) + geom_bar(alpha=0.75,fill="cornflowerblue",color="black") +
  ggtitle("number of major vessels (0-3) colored by flourosopy")
ggplot(data=data,aes(x=thal)) + geom_bar(alpha=0.75,fill="cornflowerblue",color="black") +
  ggtitle("3 = normal; 6 = fixed defect; 7 = reversable defect")
```

```{r}
ggplot(data=data,aes(trestbps)) + 
  geom_histogram(alpha=0.75,fill="seagreen",binwidth = 10) +
  ggtitle("resting blood pressure (in mm Hg on admission to the hospital)")
ggplot(data=data,aes(chol)) + 
  geom_histogram(alpha=0.75,fill="salmon",binwidth = 20) +
  ggtitle("serum cholestoral in mg/dl")
ggplot(data=data,aes(thalach)) + 
  geom_histogram(alpha=0.75,fill="gold2",binwidth = 20) +
  ggtitle("maximum heart rate achieved")
```

```{r}
ggplot(data=data,aes(x=target)) + #,colour=cp,group=cp)) + 
  geom_bar(alpha=0.75,fill="powderblue") +
  ggtitle("Distribution of Target Value (Heart disease or not)")
```

```{r}
boxplot(data$age)
```


